/**
 * Dados de demonstração do PaliVida.
 *
 * Espelham o app publicado: os 12 sintomas oficiais, os conteúdos educativos
 * completos (definição, sinais e sintomas, sinais de alerta e referências
 * bibliográficas — extraídos do documento DEFINIÇÃO_FINALIZADO_280826) e os 3
 * usuários de teste (senha "palivida123" para todos). Isso alimenta o "banco"
 * em js/db.js.
 */
window.PALIVIDA_SEED = {
  sintomas: [
    'Constipação Intestinal',
    'Fraqueza',
    'Sonolência',
    'Tristeza (Depressão)',
    'Ansiedade',
    'Dor',
    'Náusea e Vômitos',
    'Dispneia (Falta de ar)',
    'Fadiga e Cansaço',
    'Xerostomia (Boca seca)',
    'Bem Estar',
    'Anorexia e Falta de apetite',
  ],

  conteudos: [
    {
      titulo: 'Constipação Intestinal',
      descricao: 'Caracterizado por evacuações com baixa frequência, podendo ser também incompletas e difíceis.',
      sinaissintomas: [
        'Dificuldade ou incapacidade de evacuar',
        'Necessidade de fazer muita força para evacuar',
        'Menos de três evacuações por semana',
        'Eliminação de fezes endurecidas',
        'Frequência de evacuação menor do que três vezes por semana',
        'Sensação de esvaziamento incompleto do reto',
      ].join('\n'),
      sinaisalerta: [
        'Sintomas de início rápido',
        'Náuseas ou vômito',
        'Dificuldade na eliminação de flatos',
        'Dor intensa',
        'Distensão abdominal (Barriga inchada ou estufada)',
        'Perda de peso sem explicação',
        'Sangramento pelo ânus',
        'Anemia ferropriva inexplicável',
        'História familiar de câncer de cólon',
      ].join('\n'),
      referencias: [
        'OLIVEIRA, Adriana dos Santos; LOPES, Carlos Daniel Dutra; AZEVEDO, Ellen Mendes; SILVA, Gabriela Moreira da; STEFANINE, Nadia Regina; PEREIRA, Mariana Gomes; GARCIA, Mariel Henrique da Costa; DIAS, Sara Batista Andrade; QUEIROZ, Tony Souza (Org.). Sinais e sintomas na clínica médica. Palmas, TO: Unitins, 2024. Acesso em: 21 jan. 2025.',
        'TIMERMAN, Sergio. Emergências Médicas - Passo a Passo. Rio de Janeiro: Guanabara Koogan, 2019. E-book. p.284. ISBN 9788527736107. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9788527736107/. Acesso em: 21 jan. 2025.',
      ],
    },
    {
      titulo: 'Fraqueza',
      descricao: 'É a dificuldade ou incapacidade de realizar movimentos em decorrência da diminuição ou perda da força muscular.',
      sinaissintomas: [
        'Dor',
        'Falta de ar',
        'Fadiga',
        'Perda do apetite',
        'Alterações neurológicas',
        'Perca de peso',
        'Formigamento',
      ].join('\n'),
      sinaisalerta: [
        'Fraqueza muscular intensa e redução da funcionalidade',
        'Sonolência a maior parte do tempo',
      ].join('\n'),
      referencias: [
        'Instituto Nacional de Câncer (Brasil). Últimos dias de vida / Instituto Nacional de Câncer. -- Rio de Janeiro: INCA, 2023.',
        'SILVA, Eneida R R.; LUCENA, Amália F. Diagnóstico de enfermagem com base em sinais e sintomas . Porto Alegre: ArtMed, 2011. E-book. pág.202. ISBN 9788536326511. Disponível em: https://app.minhabiblioteca.com.br/reader/books/9788536326511/. Acesso em: 28 abr. 2026.',
        'CARVALHO, Ricardo Tavares de; PARSONS, Henrique Afonseca (org.). Manual de cuidados paliativos. 2. ed. São Paulo: Academia Nacional de Cuidados Paliativos (ANCP), 2012.',
      ],
    },
    {
      titulo: 'Sonolência',
      descricao: 'Redução do nível de consciência, no qual há a possibilidade do indivíduo ser acordado por estímulos',
      sinaissintomas: [
        'Alteração de sono',
        'Desempenho ineficaz nos estudos',
        'Desempenho ineficaz no trabalho',
        'Esquecimentos',
        'Prejuízo e interferências no raciocínio',
        'Prejuízo e interferências na memória',
        'Alteração nas relações familiares',
        'Alteração nas relações sociais',
        'Dificuldade de fixar e manter a atenção',
        'Prejuízo na capacidade de planejamentos',
        'Alterações em atividades que envolvam agilidade e precisão',
        'Ineficaz controle de impulsos',
        'Fadiga/Cansaço',
        'Alterações gastrointestinais',
        'Alteração do humor',
        'Aumento do Estresse',
        'Depressão',
        'Prejuízo no aprendizagem',
        'Prejuízo na interação social',
        'Prejuízo na qualidade de vida',
      ].join('\n'),
      sinaisalerta: [
        'Abertura dos olhos com muita dificuldade e momentaneamente',
        'Sonolência prolongada',
        'Redução da resposta a estímulos verbais e visuais',
        'Delirium',
        'Torpor',
        'Coma',
      ].join('\n'),
      referencias: [
        'CARVALHO, Ricardo Tavares de; PARSONS, Henrique Afonseca (org.). Manual de cuidados paliativos. 2. ed. São Paulo: Academia Nacional de Cuidados Paliativos (ANCP), 2012.',
        'BARBOSA, Sara Machado Miranda Leal et al. Prevalência de sonolência diurna excessiva e fatores associados em adolescentes da coorte RPS, em São Luís (MA). Revista Brasileira de Epidemiologia, v. 23, e200071, 2020. DOI: 10.1590/1980-549720200071.',
        'BITTENCOURT, Lia Rita Azeredo; SILVA, Rogério Santos; SANTOS, Ruth Ferreira; PIRES, Maria Laura Nogueira; MELLO, Marco Túlio de. Sonolência excessiva. Revista Brasileira de Psiquiatria, São Paulo, v. 27, supl. 1, p. 16-21, 2005.',
        'SILVA, Eneida R R.; LUCENA, Amália F. Diagnosticos de enfermagem com base em sinais e sintomas. Porto Alegre: ArtMed, 2011. E-book. p.74. ISBN 9788536326511. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9788536326511/. Acesso em: 21 jan. 2025.',
        'Manual de cuidados paliativos / Maria Perez Soares D\'Alessandro (ed.) ... [et al.]. -- 2. ed. São Paulo: Hospital Sírio-Libanês; Ministério da Saúde, 2023',
        'Instituto Nacional de Câncer (Brasil). Últimos dias de vida / Instituto Nacional de Câncer. -- Rio de Janeiro: INCA, 2023',
      ],
    },
    {
      titulo: 'Tristeza (Depressão)',
      descricao: 'Variação de humor, marcada por tristeza, falta de motivação, ansiedade, sensação de vazio, falta de vontade, motivação e esperança.',
      sinaissintomas: [
        'Humor deprimido',
        'Perda do interesse ou do prazer em atividades diárias',
        'Alterações do sono (Dormindo muito ou pouco demais)',
        'Aumento ou diminuição do apetite',
        'Alteração de peso',
        'Mudança no interesse sexual',
        'Lentificação ou agitação psicomotora observada por outras pessoas (Ficar mais lento ou agitado demais)',
        'Fadiga (Aumento do cansaço)',
        'Perda de energia',
        'Falta de concentração',
        'Incapacidade de tomar decisões',
        'Pensamentos de culpa excessiva ou baixa autoestima.',
        'Pensamentos recorrentes de morte',
        'Ideação suicida (Pensamentos de se machucar ou de não querer mais viver)',
      ].join('\n'),
      sinaisalerta: [
        'Agitação',
        'Agressividade',
        'Alteração do Nível de Consciência',
        'Desorganização',
        'Ideação ou tentativa suicida (Risco imediato de a pessoa se machucar ou colocar sua segurança em perigo.)',
      ].join('\n'),
      referencias: [
        'NUNES, Maria do Patrocínio T. D&T InforMed Clínica Médica: diagnóstico e tratamento em minutos. Barueri: Manole, 2024. E-book. p.iv. ISBN 9788520465479. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9788520465479/. Acesso em: 21 jan. 2025.',
        'TIMERMAN, Sergio. Emergências Médicas - Passo a Passo. Rio de Janeiro: Guanabara Koogan, 2019. E-book. p.416. ISBN 9788527736107. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9788527736107/. Acesso em: 21 jan. 2025.',
      ],
    },
    {
      titulo: 'Ansiedade',
      descricao: 'Mecanismo do organismo para nos avisar quando algo está errado ou com alteração. Caracterizado por tensão, hipervigilância e apreensão.',
      sinaissintomas: [
        'Preocupações excessivas',
        'Dificuldade em controlar a preocupação',
        'Dificuldade em relaxar',
        'Tensão muscular',
        'Sudorese (Suor excessivo)',
        'Sensação de falta de ar',
        'Taquipneia induzida (Aumento na respiração)',
        'Fadiga (Aumento do cansaço)',
        'Taquicardia (Coração batendo mais rápido que o normal)',
        'Hipertensão Arterial (Pressão alta)',
        'Desconforto torácico ou abdominal',
        'Dificuldade para dormir ou alterações no sono',
        'Aceleração na velocidade de fala',
        'Aceleração na velocidade do pensamento',
      ].join('\n'),
      sinaisalerta: [
        'Os sintomas não melhoram ou melhoram pouco mesmo com o tratamento;',
        'Associação ao uso abusivo, grave, de substâncias (medicamentos, álcool, drogas, entre outras)',
        'Ideação ou tentativa suicida (Risco imediato de a pessoa se machucar ou colocar sua segurança em perigo.)',
      ].join('\n'),
      referencias: [
        'NUNES, Maria do Patrocínio T. D&T InforMed Clínica Médica: diagnóstico e tratamento em minutos. Barueri: Manole, 2024. E-book. p.iv. ISBN 9788520465479. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9788520465479/. Acesso em: 21 jan. 2025.',
      ],
    },
    {
      titulo: 'Dor',
      descricao: 'É uma reação do sistema nervoso, de modo fisiológico a uma lesão tecidual, que pode ser estímulos mecânicos, químicos e térmicos.',
      sinaissintomas: [
        'Náuseas e Vômitos',
        'Sudorese (Suor excessivo)',
        'Taquicardia (Coração batendo mais rápido que o normal)',
        'Hipertensão Arterial (Pressão alta)',
        'Pele mais pálida que o habitual',
        'Alteração de tônus muscular (Músculos muito tensos ou muito relaxados)',
        'Dificuldade para dormir ou alterações no sono',
        'Ansiedade',
        'Irritabilidade',
        'Agitação',
        'Aumento ou diminuição do apetite',
        'Maior esforço ou dificuldade para respirar',
        'Aumento da frequência respiratória',
        'Lapso de consciência e de falta de atenção',
        'Sensação de queimação',
        'Sensação de peso',
        'Sensação de agulhadas e ferroadas',
        'Sensação de choques',
        'Sensação de formigamento ou adormecimento',
      ].join('\n'),
      sinaisalerta: [
        'Dor de difícil controle',
        'Dor de início súbito',
        'Incapacidade física, psicossocial e crônica',
        'Dor ou forte desconforto no peito',
        'Dor abdominal de inicio recente',
        'Alterações de humor e de comportamento',
      ].join('\n'),
      referencias: [
        'OLIVEIRA, Adriana dos Santos; LOPES, Carlos Daniel Dutra; AZEVEDO, Ellen Mendes; SILVA, Gabriela Moreira da; STEFANINE, Nadia Regina; PEREIRA, Mariana Gomes; GARCIA, Mariel Henrique da Costa; DIAS, Sara Batista Andrade; QUEIROZ, Tony Souza (Org.). Sinais e sintomas na clínica médica. Palmas, TO: Unitins, 2024. Acesso em: 21 jan. 2025.',
        'Manual de avaliação e tratamento da dor / Mauro Araújo (Org.). -- Belém : EDUEPA, 2020. 112 p. : il.',
        'CARVALHO, Ricardo Tavares de; PARSONS, Henrique Afonseca (org.). Manual de cuidados paliativos. 2. ed. São Paulo: Academia Nacional de Cuidados Paliativos (ANCP), 2012.',
        'COSTA, Ribeiro, Sabrina Corrêa da; CHAGA, Barrioso, Paula D.; DUTRA, Kreling, Gabriel A.; GALV. Manual de cuidados paliativos na prática . Barueri: Manole, 2026. E-book. pág.IV. ISBN 9788520457375. Disponível em: https://app.minhabiblioteca.com.br/reader/books/9788520457375/. Acesso em: 26 abr. 2026.',
        'SILVA, Eneida R R.; LUCENA, Amália F. Diagnóstico de enfermagem com base em sinais e sintomas . Porto Alegre: ArtMed, 2011. E-book. pág.294. ISBN 9788536326511. Disponível em: https://app.minhabiblioteca.com.br/reader/books/9788536326511/. Acesso em: 26 abr. 2026.',
      ],
    },
    {
      titulo: 'Náusea e Vômitos',
      descricao: 'Náusea é uma sensação subjetiva, caracterizada por mal-estar e incômodo que antecipa o vômito. Vômitos é eliminação forçada de conteúdo pela boca.',
      sinaissintomas: [
        'Anorexia (Falta ou perda de apetite de forma expressiva)',
        'Dor abdominal (Dor em região de barriga)',
        'Distensão abdominal (Barriga inchada ou estufada)',
        'Refluxo (Azia, queimação ou retorno do alimento/ácido para a boca)',
        'Constipação (Prisão de ventre)',
      ].join('\n'),
      sinaisalerta: [
        'Dor',
        'Febre',
        'Alteração da ingesta alimentar',
        'Perda de peso',
        'Cirurgias abdominais prévias',
        'Cefaleia (Dor de cabeça)',
        'Alterações visuais',
        'Vertigens (Tontura)',
        'Alterações neurológicas agudas',
        'Sinais de instabilidade hemodinâmica',
        'Desidratação',
      ].join('\n'),
      referencias: [
        'RIBEIRO, Sabrina Corrêa da C. Cuidados paliativos no paciente crítico. 2. ed. Barueri: Manole, 2023. E-book. p.443. ISBN 9786555768824. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9786555768824/. Acesso em: 21 jan. 2025.',
        'TIMERMAN, Sergio. Emergências Médicas - Passo a Passo. Rio de Janeiro: Guanabara Koogan, 2019. E-book. p.282. ISBN 9788527736107. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9788527736107/. Acesso em: 21 jan. 2025.',
      ],
    },
    {
      titulo: 'Dispneia (Falta de ar)',
      descricao: 'Sensação de desconforto ao respiratório, sentido como como falta de ar, desconforto em região de tórax, expiração incompleta ou aumento de esforço respiratório.',
      sinaissintomas: [
        'Ansiedade',
        'Depressão',
        'Alta emotividade',
        'Sensação de sufocação',
        'Tosse seca',
        'Tontura e desmaio',
        'Dor',
        'Pele mais pálida que o habitual',
        'Inchaço nas pernas e braços',
        'Exaustão',
        'Fraqueza generalizada',
        'Intolerância ao exercício',
        'Fraqueza muscular',
        'Dor ou forte desconforto no peito',
      ].join('\n'),
      sinaisalerta: [
        'Cianose (pele ou lábios azulados ou arroxeados)',
        'Dor torácica (Dor no peito)',
        'Secreções respiratórias audíveis ("sororoca")',
        'Confusão',
        'Falta de ar ao falar ou dificuldade para respirar, com sinais de cansaço ou exaustão;',
        'Respiração muito profunda, com suspiros frequentes, ou muito fraca, superficial e com pausas.',
      ].join('\n'),
      referencias: [
        'Berliner D, Schneider N, Welte T, Bauersachs J. The Differential Diagnosis of Dyspnea. Dtsch Arztebl Int. 2016 Dec 9;113(49):834-845. doi: 10.3238/arztebl.2016.0834. PMID: 28098068; PMCID: PMC5247680.',
        'COSTA, Ribeiro, Sabrina Corrêa da; CHAGA, Barrioso, Paula D.; DUTRA, Kreling, Gabriel A.; GALV. Manual de cuidados paliativos na prática . Barueri: Manole, 2026. E-book. pág.IV. ISBN 9788520457375. Disponível em: https://app.minhabiblioteca.com.br/reader/books/9788520457375/. Acesso em: 26 abr. 2026.',
        'RIBEIRO, Sabrina Corrêa da C. Cuidados paliativos no paciente crítico. 2. ed. Barueri: Manole, 2023. E-book. p.443. ISBN 9786555768824. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9786555768824/. Acesso em: 21 jan. 2025.',
        'CARVALHO, Ricardo Tavares de; PARSONS, Henrique Afonseca (org.). Manual de cuidados paliativos. 2. ed. São Paulo: Academia Nacional de Cuidados Paliativos (ANCP), 2012.',
      ],
    },
    {
      titulo: 'Fadiga e Cansaço',
      descricao: 'Sensação desagradável e subjetiva, que engloba cansaço a exaustão, desenvolvendo condição geral que interfere na capacidade funcional normal das pessoas.',
      sinaissintomas: [
        'Perda de massa muscular',
        'Falta de ar',
        'Anorexia',
        'Dor',
        'Náuseas e vômitos',
        'Depressão',
        'Ansiedade',
        'Dificuldade para dormir ou alterações no sono',
        'Alteração da autoestima',
        'Fraqueza corporal',
        'Sonolência',
        'Falta de disposição em atividades do cotidiano',
        'Lentidão de raciocínio',
        'Lentidão na concentração',
        'Lentidão de memória',
        'Alteração de humor',
        'Fraqueza corporal',
        'Interferência nas relações sociais',
      ].join('\n'),
      sinaisalerta: [
        'Piora na intensidade da fadiga/cansaço',
        'Redução do estado de atenção',
        'Inquietação ou sonolência excessiva, com pouca reação ou disposição.',
        'Palidez',
        'Alteração de Sinais Vitais',
      ].join('\n'),
      referencias: [
        'RIBEIRO, Sabrina Corrêa da C. Cuidados paliativos no paciente crítico. 2. ed. Barueri: Manole, 2023. E-book. p.315. ISBN 9786555768824. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9786555768824/. Acesso em: 21 jan. 2025.',
        'CARVALHO, Ricardo Tavares de; PARSONS, Henrique Afonseca (org.). Manual de cuidados paliativos. 2. ed. São Paulo: Academia Nacional de Cuidados Paliativos (ANCP), 2012.',
        'SOCIEDADE BRASILEIRA DE ONCOLOGIA CLÍNICA (SBOC). Manual de tratamento sintomático em cuidados paliativos. 2. ed. São Paulo: SBOC, 2025.',
        'Sinais e sintomas na clínica médica (livro eletrônico)/ Organizado por: Adriana dos Santos Oliveira, Carlos Daniel Dutra Lopes, Ellen Mendes Azevedo, Gabriela Moreira da Silva, Nadia Regina Stefanine, Mariana Gomes Pereira, Mariel Henrique da Costa Garcia, Sara Batista Andrade Dias, Tony Souza Queiroz -- Palmas TO: Unitins, 2024',
      ],
    },
    {
      titulo: 'Xerostomia (Boca seca)',
      descricao: 'Sensação de boca seca, ocasionado devido a diminuição de produção das glândulas salivares ou por alteração de sua composição',
      sinaissintomas: [
        'Saliva mais espessa',
        'Falta de produção de saliva',
        'Alterações do paladar',
        'Sensação de queimação',
        'Capacidade de mastigação e deglutição alterada',
        'Dificuldades para falar',
        'Gengivite (Inflamação da gengiva)',
        'Rachaduras e ressecamentos de lábios',
        'Úlceras',
        'Dor na boca, face ou região da mandíbula.',
        'Língua dolorida, seca, de coloração vermelha',
        'Rouquidão',
        'Inflamação e halitose',
      ].join('\n'),
      sinaisalerta: [
        'Infecções',
        'Piora expressiva dos sinais e sintomas',
        'Incapacidade de se alimentar',
        'Ressecamento de mucosas e peles',
        'Ressecamento de aparelho respiratório, faringe, fossas nasais e garganta',
      ].join('\n'),
      referencias: [
        'RIBEIRO, Sabrina Corrêa da C. Cuidados paliativos no paciente crítico. 2. ed. Barueri: Manole, 2023. E-book. p.484. ISBN 9786555768824. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9786555768824/. Acesso em: 21 jan. 2025.',
        'CARVALHO, Ricardo Tavares de; PARSONS, Henrique Afonseca (org.). Manual de cuidados paliativos. 2. ed. São Paulo: Academia Nacional de Cuidados Paliativos (ANCP), 2012.',
        'Xerostomia ou boca seca? [livro eletrônico]: saiba como diagnosticar e como tratar / Bianca Padilha Campanha L. Pinheiro...[et al.] ; coordenação Juliana Mariano Massuia Vizoto. -- 1. ed. -- Londrina, PR : Ed. das Autoras, 2022.',
        'FEIO, Madalena; SAPETA, Paula. Xerostomia em cuidados paliativos. Acta Médica Portuguesa, Lisboa, v. 18, n. 6, p. 459-466, 2005. Disponível em: https://www.actamedicaportuguesa.com/revista/index.php/amp/article/view/1064. Acesso em: 27 abr. 2026',
      ],
    },
    {
      titulo: 'Bem Estar',
      descricao: 'Percepção de modo positivo das suas condições de saúde',
      sinaissintomas: [
        'Dor',
        'Alteração de consciência',
        'Alteração no estado geral e saúde',
        'Conflito com suas crenças',
        'Cansaço/Fadiga',
        'Dificuldade nas atividades diárias e de locomoção',
        'Sono, ansiedade, tristeza',
        'Isolamento familiar/social',
        'Perda da autonomia e decisões',
        'Preocupações financeiras',
        'Falta de propósito',
        'Conflitos pessoais e familiares',
        'Ideação ou tentativa suicida (Risco imediato de a pessoa se machucar ou colocar sua segurança em perigo.)',
      ].join('\n'),
      sinaisalerta: [
        'Declínio importante do estado funcional, qualidade de vida, saúde mental e sentido da vida',
      ].join('\n'),
      referencias: [
        'PONTE, Ana Carolina Silva L. C.; PAIS-RIBEIRO, José Luís. O bem-estar em cuidados paliativos: perspectiva do doente versus profissionais de saúde. Psicologia, Saúde e Doenças, Lisboa, v. 15, n. 1, p. 138-154, 2014.',
        'JOHNSON, indefinido M. Ligações NANDA NOC - NIC . 3.ed. Rio de Janeiro: GEN Guanabara Koogan, 2012. E-book. pág.137. ISBN 9788595151697. Disponível em: https://app.minhabiblioteca.com.br/reader/books/9788595151697/. Acesso em: 28 abr. 2026.',
        'MELO, Rômulo Lustosa Pimenteira de; EULÁLIO, Maria do Carmo; SILVA, Hermesson Daniel Medeiros da; SILVA FILHO, José Marcos da; GONZAGA, Pamela de Sousa. Sentido de vida, dependência funcional e qualidade de vida em idosos. Revista Brasileira de Geriatria e Gerontologia, Rio de Janeiro, v. 16, n. 2, p. 239-250, 2013. DOI: https://doi.org/10.1590/S1809-98232013000200004.',
        'AFTAB, A.; LEE, E. E.; KLAUS, F.; DALY, R.; WU, T. C.; TU, X.; HUEGE, S.; JESTE, D. V. Meaning in life and its relationship with physical, mental, and cognitive functioning: a study of 1,042 community-dwelling adults across the lifespan. The Journal of Clinical Psychiatry, v. 81, n. 1, 2019. DOI: 10.4088/JCP.19m13064.',
        'ORGANIZAÇÃO MUNDIAL DA SAÚDE. WHOQOL-100: versão em português. Coordenação do Grupo WHOQOL no Brasil: Marcelo Pio de Almeida Fleck. Porto Alegre: Universidade Federal do Rio Grande do Sul.',
      ],
    },
    {
      titulo: 'Anorexia e Falta de apetite',
      descricao: 'Apresentada pela diminuição do apetite ou desejo de se alimentar',
      sinaissintomas: [
        'Perda de massa magra',
        'Perca de peso',
        'Fadiga',
        'Fraqueza',
        'Saciedade precoce',
        'Disfagia (dificuldade ou desconforto para engolir alimentos, líquidos ou saliva).',
        'Náusea',
        'Constipação(Prisão de ventre)',
        'Depressão',
        'Ansiedade',
        'Humor deprimido',
        'Alteração do olfato ou paladar',
        'Mucosites',
        'Estomatites',
        'Infecções',
        'Lesões em cavidade oral',
      ].join('\n'),
      sinaisalerta: [
        'Redução de ingesta',
        'Perda completa do apetite',
        'Perda de massa muscular e gordura em várias partes do corpo',
        'Parar de comer e diminui a aceitação de líquidos',
        'Perda da habilidade de engolir',
      ].join('\n'),
      referencias: [
        'RIBEIRO, Sabrina Corrêa da C. Cuidados paliativos no paciente crítico. 2. ed. Barueri: Manole, 2023. E-book. p.443. ISBN 9786555768824. Disponível em: https://integrada.minhabiblioteca.com.br/reader/books/9786555768824/. Acesso em: 21 jan. 2025.',
        'COSTA, Ribeiro, Sabrina Corrêa da; CHAGA, Barrioso, Paula D.; DUTRA, Kreling, Gabriel A.; GALV. Manual de cuidados paliativos na prática . Barueri: Manole, 2026. E-book. pág.IV. ISBN 9788520457375. Disponível em: https://app.minhabiblioteca.com.br/reader/books/9788520457375/. Acesso em: 26 abr. 2026.',
        'CARVALHO, Ricardo Tavares de; PARSONS, Henrique Afonseca (org.). Manual de cuidados paliativos. 2. ed. São Paulo: Academia Nacional de Cuidados Paliativos (ANCP), 2012.',
        'HINKLE, Janice L.; CHEEVER, Kerry H.; OVERBAUGH, Kristen J. Brunner & Suddarth - Tratado de Enfermagem Médico-Cirúrgica - 2 Volumes . 15. ed. Rio de Janeiro: Guanabara Koogan, 2023. E-book. pág.382. ISBN 9788527739504. Disponível em: https://app.minhabiblioteca.com.br/reader/books/9788527739504/. Acesso em: 26 abr. 2026.',
        'Thomas DR. Anorexia: aetiology, epidemiology and management in older people. Drugs Aging. 2009;26(7):557-70. doi: 10.2165/11316360-000000000-00000. PMID: 19655823.',
      ],
    },
  ],

  // senha "palivida123" para os três — texto puro só porque isto roda 100%
  // no navegador, sem servidor de verdade. Ver README do site.
  usuarios: {
    administrador: {
      nome: 'Administrador Demo',
      email: 'admin@palivida.local',
      senha: 'palivida123',
      formacao: 'Medicina',
      conselho_profissional: 'CRM',
    },
    paciente: {
      nome: 'Paciente Demo',
      email: 'paciente@palivida.local',
      senha: 'palivida123',
      cidade: 'Londrina',
      estado: 'PR',
      tipo_sanguineo: 'O+',
    },
    acompanhante: {
      nome_completo: 'Cuidador Demo',
      email: 'cuidador@palivida.local',
      senha: 'palivida123',
      relacionamento: 'filho(a)',
    },
  },

  // Registros iniciais (mesmas 4 primeiras "sintomas" x intensidades do seed original)
  registrosIniciais: [3, 7, 5, 9, 2, 6],
};
